global using System.Text.RegularExpressions;
global using Telegram.Bot;
global using Telegram.Bot.Types;
global using Free_Internet.Models;
global using Free_Internet.Services;
global using System.Timers;
global using System.Text;
global using WTelegram;
global using Starksoft.Net.Proxy;